'use strict';

// AUTO-GENERATED by scripts/generate-modules.js - do not hand-edit.
const { MeshModule } = require('./Mesh');
const { ProtocolBridgeModule } = require('./ProtocolBridge');

/**
 * Attaches every generated module to the client under its lowerCamel controller
 * name (e.g. client.completion, client.images, client.holonicMemory).
 */
function attachGeneratedModules(client, http) {
  client.mesh = client.mesh || new MeshModule(http);
  client.protocolBridge = client.protocolBridge || new ProtocolBridgeModule(http);
  return client;
}

module.exports = { attachGeneratedModules };
