// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class MeshModule {
  constructor(http: unknown);

  /** POST v1/mesh/links */
  addLink(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET v1/mesh/route */
  computeRoute(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET v1/mesh/nodes */
  getNodes(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/mesh/nodes/{nodeId}/heartbeat */
  heartbeat(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/mesh/nodes */
  registerNode(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/mesh/send */
  sendMessage(args?: Record<string, any>): Promise<OASISResponse>;
}
