'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/mesh (source: WEB8 Mesh WebAPI MeshController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class MeshModule {
  constructor(http) {
    this._http = http;

    // POST v1/mesh/links (query: nodeAId, nodeBId, latencyMs)
    this.addLink = makeOperation(http, "v1/mesh", "POST", "links", {"query":["nodeAId","nodeBId","latencyMs"]});
    // GET v1/mesh/route (query: sourceNodeId, destinationNodeId)
    this.computeRoute = makeOperation(http, "v1/mesh", "GET", "route", {"query":["sourceNodeId","destinationNodeId"]});
    // GET v1/mesh/nodes
    this.getNodes = makeOperation(http, "v1/mesh", "GET", "nodes");
    // POST v1/mesh/nodes/{nodeId}/heartbeat
    this.heartbeat = makeOperation(http, "v1/mesh", "POST", "nodes/{nodeId}/heartbeat");
    // POST v1/mesh/nodes
    this.registerNode = makeOperation(http, "v1/mesh", "POST", "nodes");
    // POST v1/mesh/send
    this.sendMessage = makeOperation(http, "v1/mesh", "POST", "send");
  }
}

module.exports = { MeshModule };
