'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/protocol-bridge (source: WEB8 Mesh WebAPI ProtocolBridgeController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class ProtocolBridgeModule {
  constructor(http) {
    this._http = http;

    // post v1/protocol-bridge/translate-inbound
    this.translateInbound = makeOperation(http, "v1/protocol-bridge", "POST", "translate-inbound");
    // post v1/protocol-bridge/translate-outbound
    this.translateOutbound = makeOperation(http, "v1/protocol-bridge", "POST", "translate-outbound");
  }
}

module.exports = { ProtocolBridgeModule };
